version: "3.8"
services:
  trading-bot:
    build: .
    container_name: trading-bot
    restart: always
    volumes:
      - ./:/app
      - ./config.yaml:/app/config.yaml
    command: python main.py